export enum Methods {
  AudioLibraryGetSongs = 'AudioLibrary.GetSongs',
  AudioLibraryGetAlbums = 'AudioLibrary.GetAlbums',
  AudioLibraryGetGenres = 'AudioLibrary.GetGenres',
  AudioLibraryGetArtists = 'AudioLibrary.GetArtists',
  PlaylistOnAdd = 'Playlist.OnAdd',
  PlaylistOnRemove = 'Playlist.OnRemove',
  PlaylistOnClear = 'Playlist.OnClear',
  PlaylistGetItems = 'Playlist.GetItems',
  PlayerGetProperties = 'Player.GetProperties',
  PlayerGetItem = 'Player.GetItem',
  GUiOnDPMSDeactivated = 'GUI.OnDPMSDeactivated',
  GUIOnScreensaverDeactivated = 'GUI.OnScreensaverDeactivated',
  PlayerOnSpeedChanged = 'Player.OnSpeedChanged',
  PlayerOnStop = 'Player.OnStop',
  PlayerOnPlay = 'Player.OnPlay',
  PlayerOnAVStart = 'Player.OnAVStart',
  PlayerOnPropertyChanged = 'Player.OnPropertyChanged',
  ApplicationSetVolume = 'Application.SetVolume',
  ApplicationGetProperties = 'Application.GetProperties',

  // VideoLibrary
  VideoLibraryGetMovies = 'VideoLibrary.GetMovies',
  VideoLibraryGetMovieDetails = 'VideoLibrary.GetMovieDetails',
  VideoLibraryGetTVShows = 'VideoLibrary.GetTVShows',
  VideoLibraryGetTVShowDetails = 'VideoLibrary.GetTVShowDetails',
  VideoLibraryGetSeasons = 'VideoLibrary.GetSeasons',
  VideoLibraryGetEpisodes = 'VideoLibrary.GetEpisodes',
  VideoLibraryGetGenres = 'VideoLibrary.GetGenres',
}
